name: Angular CI

on:
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14" # specify your Node.js version here

      - name: Install dependencies
        run: |
          cd src/Client
          npm install

      - name: Build
        run: |
          cd src/Client
          npm run build -- --prod
