name: ASP.NET Core Docker CI

on:
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x" # specify your .NET Core version here

      - name: Docker Build
        run: |
          cd src/Server
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cbc-api .
